"""Initial

Revision ID: 533adcbdf8d0
Revises: 
Create Date: 2022-10-16 16:11:54.012727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533adcbdf8d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
