"""Initial

Revision ID: 9dea0dc27525
Revises: 533adcbdf8d0
Create Date: 2022-10-16 16:47:08.409577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dea0dc27525'
down_revision = '533adcbdf8d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
